#!groovy

// Generated by IBM TransformationAdvisor
// Mon Jan 28 04:10:22 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'daytraderee6'
    mvnCommands = '--version'
    test='false'
}